import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';

export default function Home() {
    const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
            <div className={styles[`title-wrapper`]}>
                <div className={styles[`home-title`]}>
                    감정의<br/>
                    셀프 기자회견
                </div>
                <div className={styles[`home-subtitle`]}>
                    아아 이제 가면을 벗을 시간입니다.<br/>
                    꾸밈없이 내 자신에게 솔직해지세요
                </div>
            </div>
            <div className={styles[`home-image`]}>설명하는 그림</div>
            <div className={styles.authentication}>
                <button className={styles.login} onClick = {() => {router.push('/login')}}>로그인</button>
                <button className={styles.signup} onClick = {() => {router.push('/signup')}}>회원가입</button>
            </div>
        </div>
      </main>
    </div>
  )
}
